export const buttons = [
  {
    text: '',
    activeImage: '/insta-pics/activeHome.png',
    nonActiveImage: '/insta-pics/home.png',
    type: 'page',
    active: false,
  },
  {
    text: 'search',
    activeImage: '/insta-pics/search.png',
    nonActiveImage: '/insta-pics/search.png',
    type: 'component',
    active: false,
  },
  {
    text: 'explore',
    activeImage: '/insta-pics/activeExplore.png',
    nonActiveImage: '/insta-pics/explore.png',
    type: 'page',
    active: false,
  },
  {
    text: 'reels',
    activeImage: '/insta-pics/activeReels.png',
    nonActiveImage: '/insta-pics/reels.png',
    type: 'page',
    active: false,
  },
  {
    text: 'messages',
    activeImage: '/insta-pics/activeMessages.png',
    nonActiveImage: '/insta-pics/messages.png',
    type: 'page',
    active: false,
  },
  {
    text: 'notifications',
    activeImage: '/insta-pics/activeNotifications.png',
    nonActiveImage: '/insta-pics/notifications.png',
    type: 'component',
    active: false,
  },
  {
    text: 'create',
    activeImage: '/insta-pics/create.png',
    nonActiveImage: '/insta-pics/create.png',
    type: 'component',
    active: false,
  },
  {
    text: 'profile',
    activeImage: '/insta-pics/default.png',
    nonActiveImage: '/insta-pics/default.png',
    type: 'page',
    active: false,
  },
  {
    text: 'more',
    activeImage: '/insta-pics/hamburger-menu-active.png',
    nonActiveImage: '/insta-pics/hamburger-menu.png',
    type: 'component',
    active: false,
  },
];
